### PR TITLE
Add miniconda project template

### PR DESCRIPTION
**Pull request by jarq6c**
This template includes a Makefile and language-specific files used to generate reproducible Python environments to develop distributable Python packages. Instructions for use and links to further details on packaging and testing in Python are included in `README.md`. Myself and others in the org have found this type of template useful. Especially when restricted to environments with outdated or incompatible Python versions.

## Additions

 - Symlink to ../../CHANGELOG.md
 - Symlink to ../../LICENSE
 - Example package: `src/hello/hello.py`
 - Example package: `src/hello/__init__.py`
 - Symlink to ../../CONTRIBUTING.md
 - Make environment and package: `Makefile`
 - Environment packages: `requirements.txt`
 - Symlink to ../../TERMS.md
 - Example package: `EXCLUDE`
 - Example package: `MANIFEST.in`
 - Symlink to ../../SECURITY.md
 - Example test: `tests/test_hello.py`
 - Symlink to ../../INSTALL.md
 - Example package: `pyproject.toml`
 - Example package: `setup.cfg`

## Removals

- None

## Changes

- None to base template, expect addition of subdirectories

## Testing

1. Example test given.

## Notes

- None

## Todos

- If a users desires more advanced functionality or build processes, they will have to implement them. For example, the default target does not install everything needed by a hypothetical data science project like `pandas` or `Cython`. However, once the environment is set up, these are easily installed into the generated environment.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Windows
- [x] Linux
- [ ] Browser

### Accessibility

- [x] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [x] Is useable without CSS
- [x] Is useable without JS
- [x] Flexible from small to large screens
- [x] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by jarq6c** [comment]
Requesting review @ZacharyWills @hellkite500

**Comment by hellkite500** [comment]
I don't think this is the right repository for this template.  This repository is itself a template repository, meaning that new open source projects should start from a clone of this repository.  This provides the basic documentation needed for the open source project.  Adding an application specific template to this repository would propagate that to all open source projects starting from this template.  We could, and probably should, discuss a stand-alone python/conda template repository to hold this type of template.

**Comment by jarq6c** [comment]
I think that's a good idea.

**Comment by ZacharyWills** [comment]
I agree that application specific templates might be better than making updates to this one. I think this template could use some work but preferably more generic changes.

**Comment by jarq6c** [comment]
The template is hosted here: https://github.com/jarq6c/miniconda-template

**Pull request closed without merging**
